### ISSUE TITLE
댓글 기능 리팩토링

### ISSUE THREAD

**Issue by minnnidev** [minnnidev/Wote#58]
## 📌 Issue

댓글 기능 리팩토링

## 📝 To-do

- [x] 댓글 UI 리팩토링
- [x] 뷰모델 리팩토링 (API 통신 준비)
- [x] 의존성 주입 코드 작성
