### ISSUE TITLE
프로필 설정 API 통신

### ISSUE THREAD

**Issue by minnnidev** [minnnidev/Wote#7]
## 📌 Issue

프로필 설정 API 통신

## 📝 To-do

- [x] 학교 설정 open API 통신
- [x] 프로필 설정 API 통신
- [x] 설정 완료되면 자동 로그인 되도록
